### PR TITLE
Fix this library

### PR DESCRIPTION
**Pull request by simPod**
This is BC break but since it was broken before by https://github.com/garlicservices/graphql-php-tools/commit/21fabcc898cad6c46737a33038650ef74f1ad692 it doesn't matter anyway.

In that commit mentioned namespaces were changed but `use` statements remained the same so there was no way it could work.

I reverted it and cleaned up the folder structure so it properly leverages PSR-4 namespace autoloading.

Also fixed some other errors.

### CODE REVIEW

**Review by Chyslovsky — APPROVED** [review]

**Review by Chyslovsky — COMMENTED** [review]
Thanks for refactoring and contributing our idea! We appreciate that!

**Comment by simPod** [comment]
@Chyslovsky @imaximius I think you're missing git hook for packagist

https://packagist.org/packages/garlic/graphql-php-tools#dev-master

image

Here is still old commit referenced. Can you please check the sync is working?

(also this repository has issues disabled, is it intended?)

**Comment by imaximius** [comment]
Sure! Try it now

**Comment by imaximius** [comment]
Issues work as well

**Comment by simPod** [comment]
wrks, ur the best!

**Pull request merged**
